export const TERANEX_RESPONSE = {
    DEVICE: "TERANEX DEVICE:\n",
    VIDEO_INPUT: "VIDEO INPUT:\n",
    VIDEO_OUTPUT: "VIDEO OUTPUT:\n",
    ANCILLARY_DATA: "ANCILLARY DATA:\n",
    GENLOCK: "GENLOCK:\n",
};

export const TERANEX_UPDATE = {
    DEVICE: "TERANEX DEVICE:\n",
    VIDEO_INPUT: "VIDEO INPUT:\n",
    VIDEO_OUTPUT: "VIDEO OUTPUT:\n",
    ANCILLARY_DATA: "ANCILLARY DATA:\n",
    GENLOCK: "GENLOCK:\n",
};

export const TERANEX_REQUEST = {
    TERANEX_DEVICE: "TERANEX DEVICE\n\n",
    VIDEO_INPUT: "VIDEO INPUT\n\n",
    VIDEO_OUTPUT: "VIDEO OUTPUT\n\n",
    AUDIO: "AUDIO\n\n",
    VIDEO_PROC_AMP: "VIDEO PROC AMP\n\n",
    VIDEO_ADJUST: "VIDEO ADJUST\n\n",
    NOISE_REDUCTION: "NOISE REDUCTION\n\n",
    ASPECT_RATIO: "VARIABLE ASPECT RATIO:\n\n",
    ANCILLARY_DATA: "ANCILLARY DATA:\n\n",
    GENLOCK: "GENLOCK:\n\n",
};

export const TERANEX_COMMANDS_SET = {
    INFO: [
        TERANEX_REQUEST.TERANEX_DEVICE,
        TERANEX_REQUEST.VIDEO_INPUT,
        TERANEX_REQUEST.VIDEO_OUTPUT,
        TERANEX_REQUEST.ANCILLARY_DATA,
        TERANEX_REQUEST.GENLOCK,
    ],
    LIVE: [TERANEX_REQUEST.VIDEO_INPUT, TERANEX_REQUEST.VIDEO_OUTPUT],
};
